// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/aperturerobotics/pstream/pstream.proto

/*
Package pstream is a generated protocol buffer package.

It is generated from these files:
	github.com/aperturerobotics/pstream/pstream.proto

It has these top-level messages:
	Header
*/
package pstream

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Header is a message header.
type Header struct {
	MessageLen uint32 `protobuf:"fixed32,1,opt,name=message_len,json=messageLen" json:"message_len,omitempty"`
}

func (m *Header) Reset()                    { *m = Header{} }
func (m *Header) String() string            { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()               {}
func (*Header) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Header) GetMessageLen() uint32 {
	if m != nil {
		return m.MessageLen
	}
	return 0
}

func init() {
	proto.RegisterType((*Header)(nil), "pstream.Header")
}

func init() { proto.RegisterFile("github.com/aperturerobotics/pstream/pstream.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 115 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4c, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0x2c, 0x48, 0x2d, 0x2a, 0x29, 0x2d, 0x4a, 0x2d,
	0xca, 0x4f, 0xca, 0x2f, 0xc9, 0x4c, 0x2e, 0xd6, 0x2f, 0x28, 0x2e, 0x29, 0x4a, 0x4d, 0xcc, 0x85,
	0xd1, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xec, 0x50, 0xae, 0x92, 0x26, 0x17, 0x9b, 0x47,
	0x6a, 0x62, 0x4a, 0x6a, 0x91, 0x90, 0x3c, 0x17, 0x77, 0x6e, 0x6a, 0x71, 0x71, 0x62, 0x7a, 0x6a,
	0x7c, 0x4e, 0x6a, 0x9e, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x7b, 0x10, 0x17, 0x54, 0xc8, 0x27, 0x35,
	0x2f, 0x89, 0x0d, 0xac, 0xd5, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x5b, 0x5c, 0xb5, 0x6f,
	0x00, 0x00, 0x00,
}
